# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ddd54fba4e53430d40209097c37b9a22ba34b94001b139eeb19ece02a445c3e09b55a0874dab66f0622baca95c0d3fcf708c7f36085ba162ba09573ddc541453

test:
  secret_key_base: 2bf9ab9c9a34c79d2b517d5f50ede88d7ccc781384d799be747dc48f331692512f526639c82388982868d439ce369c0545b20ce56a8061f09a7aa0ea6c5f5153

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
